# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 08:34
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171231_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='ass',
            field=wagtail.wagtailcore.fields.StreamField([(b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock())], blank=True),
        ),
    ]
